apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: java-app
  name: java-app
spec:
  ports:
  - protocol: TCP
    port: 8095
    targetPort: 8095
    nodePort: 30000
  selector:
    app: java-app
  type: NodePort
